/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
export const domain={
 code:'RAG',systemName:'企业知识库与 RAG 智能问答平台',englishName:'ENTERPRISE RETRIEVAL AUGMENTED GENERATION',theme:{primary:'#335d8f',dark:'#1d2b3c',accent:'#d69a4b'},workspace:'知识智能中心 / 企业知识运营',fieldWorkspace:'研发知识空间',period:'2026-08-01 · 知识质量周报',liveText:'知识索引于 10:18 完成增量更新',fieldContextLabel:'当前空间',fieldContext:'产品研发 · 内部级',fieldUser:'林知行',fieldRole:'知识运营专员',adminUser:'许闻',adminRole:'知识平台主管',
 adminTitle:'企业知识智能运营中心',adminBreadcrumb:'知识智能 / 运营总览',adminSubtitle:'统一观察知识接入、切片索引、召回质量、问答反馈与安全引用。',exportAction:'导出知识质量简报',createAction:'新建知识空间',chartTitle:'有效问答率与目标趋势',chartSubtitle:'有依据回答 / 全部问答',chartLabels:['第1周','第2周','第3周','第4周','第5周','第6周','第7周','第8周','第9周'],loadTitle:'知识空间覆盖率',loadSubtitle:'已完成索引的有效文档比例',recordsTitle:'知识摄取任务',recordsSubtitle:'按索引进度与质量风险排序',issueTitle:'知识质量提醒',issueSubtitle:'需要知识管理员处理的异常',recordName:'摄取任务',itemName:'数据源 / 文档集',unitName:'知识空间',batchName:'处理阶段',planName:'文档数',doneName:'已索引',exceptionName:'异常切片',unitLabel:'份',
 listBreadcrumb:'知识工程 / 摄取任务',listSubtitle:'管理连接器、文档解析、切片、向量化、索引与质量验收。',listSummary:[['知识文档','18,420'],['本周新增','1,286'],['待复核引用','37'],['低质量答案','9',true]],tabs:['全部','解析中','向量化','待验收','已发布'],fieldBreadcrumb:'知识助手 / 我的工作台',fieldTitle:'研发知识问答工作台',fieldSubtitle:'当前 6 个知识域 · 42 条收藏答案 · 专员林知行',fieldSecondary:'查看引用规范',reportAction:'提交反馈',fieldNoticeTitle:'回答均附带可追溯引用',fieldNotice:'当前空间仅使用内部授权知识',steps:['数据接入','文档解析','语义切片','向量索引','质量发布'],documentAction:'查看引用片段',printAction:'导出问答记录',resourceCardTitle:'知识空间画像',resourceValueLabel:'已发布知识',resourceHealthLabel:'检索健康度',quickSubtitle:'知识工作高频入口',quickActions:[['发起问答','/shopfloor/report','上下文、引用与反馈'],['上传文档','/shopfloor/material','文件、网页与数据库'],['知识收藏','/shopfloor/resources','答案、引用与专题'],['内容纠错','/shopfloor/andon','失效、冲突与敏感内容']],
 reportDefaults:[1,0],reportTitle:'提交问答质量反馈',reportSubtitle:'记录答案有效性、引用准确度和改进建议。',reportSuccess:'反馈已进入知识质量复核队列',reportPlaceholder:'填写问题背景、缺失知识、引用错误或期望答案',reportFootnote:'反馈不会直接修改知识库，须经知识管理员复核',ruleTitle:'知识回答策略',ruleSubtitle:'RAG-RD-INTERNAL · V3.6',rules:[['最大召回','8 个切片'],['引用阈值','0.78'],['答案保留','180 天'],['敏感过滤','已启用',true]],fieldTotals:[['6','知识空间'],['42','收藏答案'],['93%','有效问答率'],['4.7','答案评分']],
 adminMenus:[['/admin','home','知识驾驶舱'],['/admin/work-orders','order','摄取任务'],['/admin/samples','box','知识空间'],['/admin/schedule','calendar','同步计划'],['/admin/methods','process','检索策略'],['/admin/reviews','quality','质量评测'],['/admin/resources','machine','模型连接'],['/admin/report','chart','问答分析']],fieldMenus:[['/shopfloor','home','知识工作台'],['/shopfloor/report','report','问答反馈'],['/shopfloor/tasks','order','最近问答'],['/shopfloor/material','box','上传文档'],['/shopfloor/resources','machine','知识收藏'],['/shopfloor/andon','risk','内容纠错',3]],moduleTitles:{tasks:['最近问答','查看问题、引用、评分和处理状态'],material:['上传文档','接入文件、网页、数据库和业务系统'],resources:['知识收藏','整理高价值答案、引用与专题'],andon:['内容纠错','登记失效、冲突、错误和敏感知识'],samples:['知识空间','维护知识域、权限和数据来源'],schedule:['同步计划','配置全量和增量索引任务'],methods:['检索策略','配置切片、召回、重排与提示模板'],reviews:['质量评测','维护黄金问题集与人工复核'],report:['问答分析','分析命中率、引用率和用户反馈']},tagline:'让企业知识可检索、可引用、可治理',storyTitle:'每一个回答，<br/>都有可信知识作为依据。',storyText:'连接企业文档、业务数据与大模型的可治理知识智能底座。',pattern:[1,3,6,8,11,14,16,19,22,24,27,31],loginStats:[['93%','有效问答率'],['18,420','已索引文档'],['4.7','答案平均评分']],loginTitle:'企业知识智能中心',adminDemo:'知识 / 评测 / 治理',fieldDemo:'问答 / 引用 / 反馈'}
export const records=[{no:'RAG-ING-260801',name:'产品研发规范知识集',code:'KB-RD-PRODUCT',unit:'研发知识空间',group:'产品与研发',plan:4280,done:3972,exception:18,due:'08-02',batch:'质量验收',status:'推进中',progress:92,priority:'关注'},{no:'RAG-ING-260804',name:'售后故障案例知识集',code:'KB-CS-CASES',unit:'客户服务空间',group:'客户成功部',plan:2360,done:2360,exception:3,due:'08-03',batch:'已发布',status:'已赢单',progress:100,priority:'正常'},{no:'RAG-ING-260812',name:'人力制度与员工手册',code:'KB-HR-POLICY',unit:'内部制度空间',group:'人力行政部',plan:916,done:704,exception:27,due:'08-05',batch:'语义切片',status:'待审核',progress:76,priority:'正常'},{no:'RAG-ING-260817',name:'实施交付方法论文档',code:'KB-DELIVERY',unit:'交付知识空间',group:'交付中心',plan:1850,done:1264,exception:46,due:'08-04',batch:'向量索引',status:'风险跟进',progress:68,priority:'加急'}]
export const resources=[{code:'KB-RD-001',name:'研发知识空间',unit:'产品与研发',status:'运行中',health:94,value:'7,432',valueUnit:'份',note:'增量索引每 30 分钟执行'},{code:'KB-CS-002',name:'客户服务空间',unit:'客户成功部',status:'运行中',health:91,value:'4,286',valueUnit:'份',note:'故障案例覆盖率较高'},{code:'KB-HR-003',name:'内部制度空间',unit:'人力行政部',status:'复核',health:72,value:'1,364',valueUnit:'份',note:'部分制度即将失效'}]
export const reviews=[{no:'EVAL-260801-032',title:'研发规范黄金问题集评测',type:'引用准确性',detail:'200 题 · 许闻',result:'待确认'},{no:'EVAL-260801-011',title:'售后助手回归评测',type:'答案完整性',detail:'96.2% · 林知行',result:'通过'},{no:'EVAL-260728-018',title:'制度问答敏感信息检测',type:'安全边界',detail:'发现 4 条风险',result:'异常'}]
export const adminMetrics=[['今日知识问答','8,642','较昨日增长 12.6%','blue'],['有效问答率','93.4%','目标 92%','green'],['已索引文档','18,420','本周新增 1,286','orange'],['待处理反馈','37','9 条高优先级','red']],fieldMetrics=[['今日问答','28','已收藏 6 条','blue'],['引用覆盖','96%','全部可追溯','green'],['待复核反馈','3','1 条高优先级','orange'],['空间权限','内部级','脱敏策略已启用','slate']],chartActual=[82,84,86,88,90,91,92,93,93],chartTarget=[84,85,86,87,88,89,90,91,92],loads=[['研发知识空间',96,'7,432 份有效文档'],['客户服务空间',93,'4,286 份有效文档'],['交付知识空间',84,'3,180 份有效文档'],['内部制度空间',76,'1,364 份有效文档']],issues=[{type:'失效',title:'12 份产品规范将在 7 天内失效',detail:'涉及研发知识空间 · 等待责任人更新',status:'待更新'},{type:'冲突',title:'差旅报销标准存在版本冲突',detail:'命中 3 份制度 · 已暂停相关回答',status:'复核中'},{type:'质量',title:'售后助手出现低置信度聚集',detail:'影响 26 个相似问题',status:'优化中'}]
